services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - API_BASE_URL=http://api:8000
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./VERSION:/app/VERSION:ro
      - ./.git:/app/.git:ro
    environment:
      - PYTHONPATH=/app
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
