services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - API_BASE_URL=http://api:8000
    volumes:
      - ./web/src:/app/src:delegated
      - ./web/public:/app/public:delegated
      - ./web/next.config.ts:/app/next.config.ts:delegated
      - ./web/package.json:/app/package.json:delegated
      - ./web/tsconfig.json:/app/tsconfig.json:delegated
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./VERSION:/app/VERSION:ro
      - ./.git:/app/.git:ro
    environment:
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://ollama:11434
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      ollama:
        condition: service_healthy
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  ollama_data:
