name: Pylint Code Analysis

on:
  push:
    paths:
      - 'api/**/*.py'
  pull_request:
    paths:
      - 'api/**/*.py'

jobs:
  pylint:
    name: Python Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'api/requirements.txt'
      
      - name: Install dependencies
        working-directory: ./api
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      
      - name: Run pylint on API code
        working-directory: ./api
        run: |
          pylint app/ --output-format=text --reports=y --fail-under=9.0 --errors-only
